### PR TITLE
add : Add CODEOWNERS

### PR DESCRIPTION
**Pull request by kuro11pow2**
Reviewers are automatically registered during PR according to the contents of CODEOWNERS.

### CODE REVIEW

**Review by judemin — APPROVED** [review]
Nice work!

**Comment by kmsaidev** [comment]
I think this will be very comfortable. Thank you.

**Review by eunzinn — APPROVED** [review]
I learned about 'CODEOWNER' for the first time. Thanks :)

**Review by kmsaidev — APPROVED** [review]
I think this will be very comfortable. Thank you.

**Pull request merged**
