### PR TITLE
fix : fix to resolve conflict

### PR DESCRIPTION
**Pull request by eunzinn**
I'm going to upload without the manifest file first because I think it's going to conflict!

### CODE REVIEW

**Review by judemin — APPROVED** [review]
Nice work, we can now merge and complete sample project.

**Comment by kmsaidev** [comment]
> Nice work, we can now merge and complete sample project.

I agree with this opinion.

**Review by kuro11pow2 — APPROVED** [review]
Good job!

**Review by kmsaidev — APPROVED** [review]
Nice work!

**Pull request merged**
